### ISSUE TITLE
关于QQ知道插件的建议

### ISSUE THREAD

**Issue by jerryyang-git** [yiyungent/KnifeHub#12]
使用下来，暂时有两个建议
使用场景：问题帮助机器人
1. 在编辑关键词回复的时候可以在HUB后台直接加，感觉在群里#问#答添加有点那啥，而且还不能批量
2. 虽然可以答案相同，可以重复添加相同答案不同问的词库，但还是希望给一个`#答`添加更多的关键字

> 当然上方问题可以使用茉莉插件配合茉莉的词库功能解决，但Issues是对于单独这个插件的建议（小声

**Comment by yiyungent** [comment]
感谢建议！已加入todolist
