### ISSUE TITLE
KonataPlugin登录QQ后，几秒后又自动离线，怎么回事？

### ISSUE THREAD

**Issue by bighammer-link** [yiyungent/KnifeHub#18]

**Comment by yiyungent** [comment]
显示已在线过吗？然后又离线了？是不是你用机器人QQ登录安卓了，KonataPlugin 用的QQ安卓协议/平板协议，具体我也不清楚
![image](https://user-images.githubusercontent.com/16939388/213065341-53609f6a-d8a8-4b95-876b-bb57a2a6d4c3.png)

**Comment by yiyungent** [comment]
试试用 KonataApp 获取 BotKeyStore.json ，然后通过配置的方式登录试试，这个比较稳定，成功率高，不行就只有问 Konata.Core 官方了

**Comment by bighammer-link** [comment]
> 试试用 KonataApp 获取 BotKeyStore.json ，然后通过配置的方式登录试试，这个比较稳定，成功率高，不行就只有问 Konata.Core 官方了

好的 谢谢

**Comment by yiyungent** [comment]
> > 试试用 KonataApp 获取 BotKeyStore.json ，然后通过配置的方式登录试试，这个比较稳定，成功率高，不行就只有问 Konata.Core 官方了
> 
> 好的 谢谢

> README 下方文档有写的，如果 KonataApp 都没有办法登录上线，那么请到 https://t.me/konachan_wifi 这反馈，或者我可以私发你 Konata.Core 的官方QQ群号

可 下载 [Releases - KonataApp - Assets](https://github.com/yiyungent/KnifeHub/releases?q=KonataApp&expanded=true) 在本地登录成功后,
获取 **BotKeyStore.json** 后, 在登录页面使用 **配置** 方式登录

> *   大部分人电脑为 `Windows 64 位`, 点击 **KonataApp-win-x64.zip** 下载即可, 下载到本地解压, 双击 **KonataApp.exe**
> *   运行 `KonataApp.exe` 会自动给出输入提示, 按提示操作即可
> *   运行 `KonataApp.exe` 无需额外安装 `.NET SDK 或 Runtime`, 程序已打包
